mongodb:
  environment:
  - TZ=Australia/Sydney
  - TERM=xterm
  image: mongo:2.6
  volumes:
  - ../../data/mongodb:/data/db
  - ../../data-archive/:/backups

logstash:
  command: logstash -f /usr/share/logstash/logstash.conf
  environment:
  - TZ=Australia/Sydney
  - TERM=xterm
  image: logstash:1.5
  volumes:
  - ./logstash:/usr/share/logstash

kibana:
  build: kibana
  environment:
  - TZ=Australia/Sydney
  - TERM=xterm
  restart: always

elastic:
  command: elasticsearch
  environment:
  - ES_HEAP_SIZE=2g
  - TZ=Australia/Sydney
  - TERM=xterm
  image: elasticsearch:2.4
  volumes:
  - ../../data/elastic:/usr/share/elasticsearch/data
  - ../../data-archive/:/backups

superdesk:
  build: ../
  environment:
  - TZ=Australia/Sydney
  - TERM=xterm
  - SUPERDESK_URL=http://127.0.0.1/api
  - SUPERDESK_WS_URL=ws://127.0.0.1/ws
  - CONTENTAPI_URL=http://127.0.0.1/capi
  - SUPERDESK_CLIENT_URL=http://127.0.0.1
  - SUPERDESK_TESTING=True
  - DEFAULT_SOURCE_VALUE_FOR_MANUAL_ARTICLES=AAP
  - ODBC_PUBLISH=True
  - MONGO_URI=mongodb://mongodb/superdesk
  - LEGAL_ARCHIVE_URI=mongodb://mongodb/superdesk_la
  - ARCHIVED_URI=mongodb://mongodb/superdesk_ar
  - CONTENTAPI_MONGO_URI=mongodb://mongodb/superdesk_ca
  - ELASTICSEARCH_URL=http://elastic:9200
  - ELASTICSEARCH_INDEX=superdesk
  - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
  - CELERY_RESULT_BACKEND=amqp://guest:guest@rabbitmq:5672//
  - REDIS_URL=amqp://guest:guest@rabbitmq:5672//
  - LOG_SERVER_ADDRESS=logstash
  - LOG_SERVER_PORT=5555
  - AMAZON_ACCESS_KEY_ID
  - AMAZON_CONTAINER_NAME
  - AMAZON_REGION
  - AMAZON_SECRET_ACCESS_KEY
  - REUTERS_USERNAME
  - REUTERS_PASSWORD
  - MAIL_SERVER=mail-relay.aap.com.au
  - MAIL_PORT=25
  - MAIL_USE_TLS=false
  - MAIL_USE_SSL=false
  - SENTRY_DSN
  - VIEW_DATE_FORMAT
  - VIEW_TIME_FORMAT
  volumes:
  - ../../deploy/results/server/unit:/opt/superdesk/results-unit/
  - ../../deploy/results/server/behave:/opt/superdesk/results-behave/
  - ../../deploy/results/client/unit:/opt/superdesk/client/unit-test-results
  - /var/input/:/var/input/
  - /var/ingest/:/var/ingest/

rabbitmq:
  environment:
  - TZ=Australia/Sydney
  - TERM=xterm
  hostname: HOSTNAME
  image: rabbitmq-plus:3-management
  volumes:
  - ../../data/rabbitmq:/var/lib/rabbitmq

