rest: gunicorn -c gunicorn_config.py wsgi
wamp: python3 -u ws.py
work: celery -A worker worker -Q default
expiry: celery -A worker worker -Q expiry
legal: celery -A worker worker -Q legal
publish: celery -A worker worker -Q publish
ingest: celery -A worker worker -Q ingest
beat: celery -A worker beat
capi: gunicorn -b 0.0.0.0:5400 -c gunicorn_config.py content_api.wsgi
