rest: gunicorn -c gunicorn_config.py wsgi
wamp: python3 -u ws.py
work: celery -A worker -Q default  worker
expiry: celery -A worker -Q expiry  worker
legal: celery -A worker -Q legal  worker
publish: celery -A worker -Q publish  worker
beat: celery -A worker beat --pid=
capi: gunicorn -b 0.0.0.0:5400 -c gunicorn_config.py content_api.wsgi
